# Generated by Django 4.2 on 2023-04-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reference',
            new_name='reference_id',
        ),
    ]
